// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Scheduling.Models;

public partial class Function
{
    public int FunctionId { get; set; }

    public string FunctionName { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<RoleFunction> RoleFunctions { get; set; } = new List<RoleFunction>();
}