// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Scheduling.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int? UserId { get; set; }

    public int WorkId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public DateOnly ScheduleDate { get; set; }

    public string Note { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public string Status { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual User User { get; set; }

    public virtual Work Work { get; set; }
}