// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Scheduling.Models;

public partial class SchedulingContext : DbContext
{
    public SchedulingContext(DbContextOptions<SchedulingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Function> Functions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleFunction> RoleFunctions { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Work> Works { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Function>(entity =>
        {
            entity.HasKey(e => e.FunctionId).HasName("PK__Function__31ABFAF82202A408");

            entity.Property(e => e.FunctionName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1AAF896B27");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160A4D07E1E").IsUnique();

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RoleFunction>(entity =>
        {
            entity.HasKey(e => e.RoleFunctionId).HasName("PK__RoleFunc__8859C71DA78D7468");

            entity.ToTable("RoleFunction");

            entity.HasOne(d => d.Function).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.FunctionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RoleFunct__Funct__4CA06362");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFunctions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RoleFunct__RoleI__4BAC3F29");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId).HasName("PK__Schedule__9C8A5B49D92F6F86");

            entity.ToTable("Schedule");

            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("active");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ScheduleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__Schedule__Create__49C3F6B7");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.ScheduleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK__Schedule__Update__4AB81AF0");

            entity.HasOne(d => d.User).WithMany(p => p.ScheduleUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Schedule__UserId__47DBAE45");

            entity.HasOne(d => d.Work).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.WorkId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Schedule__WorkId__48CFD27E");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CA2063F0E");

            entity.HasIndex(e => e.UserEmail, "UQ__Users__08638DF86B071445").IsUnique();

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordSalt).HasMaxLength(255);
            entity.Property(e => e.UserEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleId__46E78A0C");
        });

        modelBuilder.Entity<Work>(entity =>
        {
            entity.HasKey(e => e.WorkId).HasName("PK__Work__2DE6D5F58929F846");

            entity.ToTable("Work");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.WorkLocation).HasMaxLength(100);
            entity.Property(e => e.WorkName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.WorkNote).HasMaxLength(255);
            entity.Property(e => e.WorkType)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}