// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Scheduling.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserEmail { get; set; }

    public string UserPassword { get; set; }

    public string PasswordSalt { get; set; }

    public string UserName { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<Schedule> ScheduleCreatedByNavigations { get; set; } = new List<Schedule>();

    public virtual ICollection<Schedule> ScheduleUpdatedByNavigations { get; set; } = new List<Schedule>();

    public virtual ICollection<Schedule> ScheduleUsers { get; set; } = new List<Schedule>();
}