// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Scheduling.Models;

public partial class Work
{
    public int WorkId { get; set; }

    public string WorkName { get; set; }

    public string WorkNote { get; set; }

    public bool IsActive { get; set; }

    public TimeOnly? DefaultStartTime { get; set; }

    public TimeOnly? DefaultEndTime { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string WorkLocation { get; set; }

    public string WorkType { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}